services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: expressjs
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: