services:
  postgres:
    container_name: postgresql
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: ${PG_DB}
      POSTGRESQL_USERNAME: ${PG_USER}
      POSTGRESQL_PASSWORD: ${PG_PASS}
      POSTGRESQL_POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRESQL_TIMEZONE: ${TZ}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: