services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: