on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: npm install, run tests with coverage
      run: |
        npm install
        npm run test:push

    - name: Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}